const UserShiftSchedule = require('./calendar.model');
const WorkoutLog = require('../workout/workoutLog.model');
const Meal = require('../nutrition/meal.model');
const SleepLog = require('../sleep-recovery/sleepLog.model');
const User = require('../user/user.model');
const Shift = require('../onboarding/shift.model');
const Workout = require('../workout/workout.model');
const WellnessEngine = require('../engine/wellnessEngine.service');
const logger = require('../../utils/logger');
const mongoose = require('mongoose');

class CalendarService {
  /**
   * Generate schedule for user based on shift pattern
   */
  static async generateSchedule(userId, startDate, endDate) {
    try {
      const user = await User.findById(userId);
      if (!user || !user.shiftType) {
        throw new Error('User or shift type not found');
      }

      const shift = await Shift.findOne({ name: user.shiftType });
      if (!shift) {
        throw new Error('Shift configuration not found');
      }

      const schedule = [];
      const scheduleStartDate = new Date(startDate);
      scheduleStartDate.setHours(0, 0, 0, 0);
      const currentDate = new Date(scheduleStartDate);
      const end = new Date(endDate);
      end.setHours(23, 59, 59, 999);

      while (currentDate <= end) {
        let dayType = 'off';

        // Determine day type based on shift pattern
        if (user.shiftType === 'fixed_night') {
          // Fixed night: work Monday-Friday, off Saturday-Sunday
          const dayOfWeek = currentDate.getDay();
          dayType = dayOfWeek >= 1 && dayOfWeek <= 5 ? 'work' : 'off';
        } else if (user.shiftType === 'rotating') {
          // Rotating: 4 days work, 3 days off pattern
          const daysSinceStart = Math.floor((currentDate - scheduleStartDate) / (1000 * 60 * 60 * 24));
          dayType = daysSinceStart % 7 < 4 ? 'work' : 'off';
        } else if (user.shiftType === 'early_morning') {
          // Early morning: work Monday-Friday, off Saturday-Sunday
          const dayOfWeek = currentDate.getDay();
          dayType = dayOfWeek >= 1 && dayOfWeek <= 5 ? 'work' : 'off';
        }

        // Create or update schedule entry
        const scheduleEntry = await UserShiftSchedule.findOneAndUpdate(
          { userId, date: currentDate },
          {
            userId,
            date: new Date(currentDate),
            dayType,
            taskType: dayType === 'work' ? 'fixed' : 'suggested',
            title: dayType === 'work' ? 'Shift plan' : 'Recovery / off day',
            description:
              dayType === 'work'
                ? `Stay aligned with your ${user.shiftType} shift.`
                : 'Use this day to recover, meal prep, or catch up on sleep.',
            shiftStart: dayType === 'work' ? shift.defaultWakeTime : null,
            shiftEnd: dayType === 'work' ? shift.defaultSleepTime : null,
            scheduledStart: dayType === 'work' ? new Date(currentDate) : null,
            scheduledEnd: dayType === 'work' ? new Date(currentDate) : null,
            sourceModule: 'onboarding',
            sourceId: user.shiftType,
            dependency: null,
            status: dayType === 'work' ? 'fixed' : 'suggested',
            priority: dayType === 'work' ? 'high' : 'medium',
            deepLink: '/calendar',
            isAutoGenerated: true,
          },
          { upsert: true, returnDocument: 'after' },
        );

        schedule.push(scheduleEntry);
        currentDate.setDate(currentDate.getDate() + 1);
      }

      return schedule;
    } catch (error) {
      logger.error(`Generate schedule error: ${error.message}`);
      throw error;
    }
  }

  /**
   * Get monthly calendar view
   */
  static async getMonthView(userId, year, month) {
    try {
      // Calculate start and end dates for the month
      const startDate = new Date(year, month - 1, 1);
      const endDate = new Date(year, month, 0);

      // Get schedule for the month
      const schedule = await UserShiftSchedule.find({
        userId,
        date: { $gte: startDate, $lte: endDate },
      }).sort({ date: 1 });

      // Format month view data
      const monthData = {
        year,
        month,
        monthName: startDate.toLocaleString('default', { month: 'long' }),
        days: [],
      };

      // Create array for all days in month
      const currentDate = new Date(startDate);
      while (currentDate <= endDate) {
        const daySchedule = schedule.find(s => s.date.toDateString() === currentDate.toDateString());

        monthData.days.push({
          date: new Date(currentDate),
          dayOfMonth: currentDate.getDate(),
          dayOfWeek: currentDate.toLocaleString('default', { weekday: 'short' }),
          dayType: daySchedule?.dayType || 'off',
          isToday: currentDate.toDateString() === new Date().toDateString(),
        });

        currentDate.setDate(currentDate.getDate() + 1);
      }

      return monthData;
    } catch (error) {
      logger.error(`Get month view error: ${error.message}`);
      throw error;
    }
  }

  /**
   * Get daily timeline
   */
  static async getDailyTimeline(userId, date, filter = 'all') {
    try {
      const queryDate = new Date(date);
      queryDate.setHours(0, 0, 0, 0);

      // Get day type from schedule and user data
      const [schedule, user] = await Promise.all([
        UserShiftSchedule.findOne({
          userId,
          date: queryDate,
        }),
        User.findById(userId).select('shiftType'),
      ]);

      const dayType = schedule?.dayType || 'off';

      // Fetch all events for the day
      const [workouts, meals, sleepRecovery] = await Promise.all([
        WorkoutLog.find({
          userId,
          date: queryDate,
        }).populate('workoutId', 'title category durationMinutes'),

        Meal.find({
          userId,
          date: queryDate,
        }).populate('foodId', 'name'),

        SleepLog.find({
          userId,
          date: queryDate,
        }),
      ]);

      // Calculate readiness score
      let readiness = 75;
      try {
        const wellnessContext = await WellnessEngine.buildContext(userId);
        if (wellnessContext && wellnessContext.scores) {
          readiness = wellnessContext.scores.readiness;
        }
      } catch (err) {
        logger.error(`Readiness score fetch error in calendar: ${err.message}`);
      }

      // Process events
      const events = [];

      // Process workouts
      workouts.forEach(workout => {
        const time = workout.scheduledTime || '09:00'; // Default time if not scheduled
        const status = workout.completed ? 'done' : workout.status || 'scheduled';

        // Generate dynamic subtitle
        const subtitle = this.generateDynamicSubtitle(
          'workout',
          workout,
          user,
          schedule,
          sleepRecovery,
          time,
        );

        events.push({
          id: workout._id,
          type: 'workout',
          time,
          title: workout.workoutId?.title || 'Workout',
          subtitle,
          status,
          data: workout,
        });
      });

      // Process meals
      meals.forEach(meal => {
        const time = meal.scheduledTime || '12:00'; // Default time if not scheduled

        // Generate dynamic subtitle
        const subtitle = this.generateDynamicSubtitle('meal', meal, user, schedule, sleepRecovery, time);

        events.push({
          id: meal._id,
          type: 'meal',
          time,
          title: meal.title,
          subtitle,
          status: meal.status || 'logged',
          data: meal,
        });
      });

      // Process sleep/recovery activities
      sleepRecovery.forEach(activity => {
        const time = activity.startTime;

        // Generate dynamic subtitle
        const subtitle = this.generateDynamicSubtitle(
          'recovery',
          activity,
          user,
          schedule,
          sleepRecovery,
          time,
        );

        events.push({
          id: activity._id,
          type: 'recovery',
          time,
          title: activity.title,
          subtitle,
          status: activity.status || 'logged',
          data: activity,
        });
      });

      const shift = user?.shiftType ? await Shift.findOne({ name: user.shiftType }) : null;
      const shiftStart = schedule?.shiftStart || shift?.defaultWakeTime || '08:00';
      const shiftEnd = schedule?.shiftEnd || shift?.defaultSleepTime || '16:00';

      // Dynamically orchestrate recommendations if on-shift work day
      if (filter === 'on_shift' && dayType === 'work') {
        const isToday = queryDate.toDateString() === new Date().toDateString();
        const now = new Date();
        const nowStr = `${now.getHours().toString().padStart(2, '0')}:${now.getMinutes().toString().padStart(2, '0')}`;
        const nowMinutes = now.getHours() * 60 + now.getMinutes();

        const shiftStartMin = this.timeToMinutes(shiftStart);

        // Helper to compute minutes relative to shift start (-720 to +720 range)
        const getRelativeMinutes = (timeMinutes) => {
          let diff = timeMinutes - shiftStartMin;
          if (diff < -720) diff += 1440;
          if (diff > 720) diff -= 1440;
          return diff;
        };

        const nowRelative = getRelativeMinutes(nowMinutes);

        // Helper: check if we already have a scheduled or logged database equivalent to avoid duplicate
        const hasDbPreShift = meals.some(m => m.mealType === 'pre_workout' && m.scheduledTime);
        const hasDbLunch = meals.some(m => m.mealType === 'post_workout' && m.scheduledTime);
        const hasDbWorkout = workouts.some(w => w.scheduledTime);
        const hasDbRecovery = sleepRecovery.some(log => (log.activityKey === 'wind_down' || log.activityKey === 'active_recovery') && log.startTime);

        // 1. Pre-Shift Energizer
        if (!hasDbPreShift) {
          const task1Time = this.addMinutesToTime(shiftStart, -60);
          const completed = meals.some(m => m.mealType === 'pre_workout');
          let status = completed ? 'completed' : 'suggested';
          let title = 'Pre-Shift Energizer & Hydration';
          let subtitle = 'Pre-Shift Fuel • Light meal + electrolytes';

          if (isToday && !completed) {
            const t1Min = this.timeToMinutes(task1Time);
            const t1Relative = getRelativeMinutes(t1Min);
            if (nowRelative > t1Relative + 60) {
              status = 'downgraded';
              title = 'Hydration Reset & Breathwork';
              subtitle = 'Lighter intervention • Missed energy window, focus on deep breathing';
            }
          }

          events.push({
            id: 'rec_pre_shift_energizer',
            type: 'meal',
            time: task1Time,
            title,
            subtitle,
            status,
            isRecommended: true,
            data: { mealType: 'pre_workout' }
          });
        }

        // 2. Mid-Shift Lunch
        if (!hasDbLunch) {
          const task2Time = this.addMinutesToTime(shiftStart, 240);
          const completed = meals.some(m => {
            const mealMin = this.timeToMinutes(m.scheduledTime || '12:00');
            const startMin = this.timeToMinutes(shiftStart);
            const endMin = this.timeToMinutes(shiftEnd);
            return m.mealType === 'post_workout' || (mealMin >= startMin && mealMin <= endMin);
          });
          let status = completed ? 'completed' : 'suggested';

          if (isToday && !completed) {
            const t2Min = this.timeToMinutes(task2Time);
            const t2Relative = getRelativeMinutes(t2Min);
            if (nowRelative > t2Relative + 60) {
              status = 'missed';
            }
          }

          events.push({
            id: 'rec_mid_shift_lunch',
            type: 'meal',
            time: task2Time,
            title: 'Mid-Shift Balanced Meal',
            subtitle: 'Energy Refuel • Slow-digesting carbs & lean protein',
            status,
            isRecommended: true,
            data: { mealType: 'post_workout' }
          });
        }

        // 3. Mid-Shift Workout / Stretch
        if (!hasDbWorkout) {
          const task3Time = this.addMinutesToTime(shiftStart, 270);
          const completed = workouts.length > 0 || sleepRecovery.some(log => log.activityKey === 'active_recovery');
          
          let taskType = readiness >= 65 ? 'workout' : 'recovery';
          let title = readiness >= 65 ? 'Mid-Shift Express Workout' : 'Mid-Shift Active Recovery Stretch';
          let subtitle = readiness >= 65
            ? '20 min • Moderate intensity workout allowed by readiness'
            : '10 min • Low intensity mobility & posture reset';
          let status = completed ? 'completed' : 'suggested';

          if (isToday && !completed) {
            const t3Min = this.timeToMinutes(task3Time);
            const t3Relative = getRelativeMinutes(t3Min);
            if (nowRelative > t3Relative + 60) {
              // Missed: Downgrade and push forward to current time + 10 mins
              status = 'downgraded';
              taskType = 'recovery';
              title = 'Mid-Shift Active Recovery Stretch & Mobility';
              subtitle = 'Lighter intervention • Pushed forward due to missed slot';
              events.push({
                id: 'rec_mid_shift_workout',
                type: taskType,
                time: this.addMinutesToTime(nowStr, 10),
                title,
                subtitle,
                status,
                isRecommended: true,
                data: {}
              });
            } else {
              events.push({
                id: 'rec_mid_shift_workout',
                type: taskType,
                time: task3Time,
                title,
                subtitle,
                status,
                isRecommended: true,
                data: {}
              });
            }
          } else {
            events.push({
              id: 'rec_mid_shift_workout',
              type: taskType,
              time: task3Time,
              title,
              subtitle,
              status,
              isRecommended: true,
              data: {}
            });
          }
        }

        // 4. Post-Shift Wind Down
        if (!hasDbRecovery) {
          const task4Time = this.addMinutesToTime(shiftEnd, 30);
          const completed = sleepRecovery.some(log => log.activityKey === 'wind_down');
          let status = completed ? 'completed' : 'suggested';

          if (isToday && !completed) {
            const t4Min = this.timeToMinutes(task4Time);
            const t4Relative = getRelativeMinutes(t4Min);
            if (nowRelative > t4Relative + 60) {
              status = 'missed';
            }
          }

          events.push({
            id: 'rec_post_shift_wind_down',
            type: 'recovery',
            time: task4Time,
            title: 'Post-Shift Recovery & Sleep Prep',
            subtitle: 'Wind Down • Melatonin support / chamomile tea',
            status,
            isRecommended: true,
            data: {}
          });
        }
      }

      // Dynamically orchestrate recommendations if off-shift day
      if (filter === 'off_shift' && dayType !== 'work') {
        const isToday = queryDate.toDateString() === new Date().toDateString();
        const now = new Date();
        const nowStr = `${now.getHours().toString().padStart(2, '0')}:${now.getMinutes().toString().padStart(2, '0')}`;
        const nowMinutes = now.getHours() * 60 + now.getMinutes();

        // 1. Morning Reset (09:00)
        const t1Str = '09:00';
        const t1Min = this.timeToMinutes(t1Str);
        let t1Status = 'suggested';
        if (isToday && nowMinutes > t1Min + 60) {
          t1Status = 'missed';
        }
        events.push({
          id: 'rec_offshift_morning_reset',
          type: 'recovery',
          time: t1Str,
          title: 'Morning Reset & Mobility',
          subtitle: 'Light stretching to wake up the body',
          status: t1Status,
          isRecommended: true,
          data: {}
        });

        // 2. Nutritional Reset (13:00)
        const t2Str = '13:00';
        const t2Min = this.timeToMinutes(t2Str);
        let t2Status = 'suggested';
        if (isToday && nowMinutes > t2Min + 60) {
          t2Status = 'missed';
        }
        events.push({
          id: 'rec_offshift_nutrition_prep',
          type: 'meal',
          time: t2Str,
          title: 'Nutritional Reset & Hydration',
          subtitle: 'Focus on balanced macros and meal prep for the week',
          status: t2Status,
          isRecommended: true,
          data: { mealType: 'lunch' }
        });

        // 3. Main Activity (16:00) - based on readiness
        const t3Str = '16:00';
        const t3Min = this.timeToMinutes(t3Str);
        let t3Status = 'suggested';
        let t3Time = t3Str;
        let t3Type = readiness >= 75 ? 'workout' : 'recovery';
        let t3Title = readiness >= 75 ? 'Zone 2 Cardio / Active Recovery' : 'Deep Recovery Yoga';
        let t3Subtitle = readiness >= 75 
          ? 'Maintain conditioning without high CNS fatigue'
          : 'Prioritize healing • Low intensity stretch flow';

        if (isToday && nowMinutes > t3Min + 60) {
          t3Status = 'downgraded';
          t3Type = 'recovery';
          t3Title = 'Evening Restorative Stretch';
          t3Subtitle = 'Pushed from afternoon • Gentle nervous system reset';
          t3Time = this.addMinutesToTime(nowStr, 10);
        }

        events.push({
          id: 'rec_offshift_main_activity',
          type: t3Type,
          time: t3Time,
          title: t3Title,
          subtitle: t3Subtitle,
          status: t3Status,
          isRecommended: true,
          data: {}
        });

        // ACTION PIPELINE: Issue proactive reminder if within 1 hour
        if (isToday && t3Status === 'suggested' && t3Type === 'recovery' && (t3Min - nowMinutes) <= 60 && (t3Min - nowMinutes) >= 0) {
          WellnessEngine.recordEvent({
            userId,
            type: 'SLEEP_RECOVERY',
            category: 'sleep',
            title: `Upcoming: ${t3Title}`,
            message: t3Subtitle,
            sourceModule: 'calendar',
            sourceId: 'rec_offshift_main_activity',
            deepLink: '/sleeprecovery',
            priority: 'MEDIUM',
            dedupeKey: `sleep_reminder:main_activity:${queryDate.toISOString().slice(0, 10)}`,
            payload: {},
          }).catch(() => {});
        }

        // 4. Sleep Prep (21:00)
        const t4Str = '21:00';
        const t4Min = this.timeToMinutes(t4Str);
        let t4Status = 'suggested';
        if (isToday && nowMinutes > t4Min + 60) {
          t4Status = 'missed';
        }
        events.push({
          id: 'rec_offshift_sleep_prep',
          type: 'recovery',
          time: t4Str,
          title: 'Sleep Prep & Wind Down',
          subtitle: 'Disconnect from screens • Deep breathing',
          status: t4Status,
          isRecommended: true,
          data: {}
        });
      }

      // Apply filters
      let filteredEvents = events;
      if (filter === 'shift_cycle') {
        // Show all events
      } else if (filter === 'on_shift') {
        filteredEvents = events.filter(
          event =>
            event.isRecommended ||
            event.type === 'workout' ||
            (event.type === 'meal' && ['pre_workout', 'post_workout'].includes(event.data.mealType)),
        );
      } else if (filter === 'off_shift') {
        filteredEvents = events.filter(
          event =>
            event.isRecommended ||
            (event.type === 'recovery' ||
              (event.type === 'meal' && !['pre_workout', 'post_workout'].includes(event.data.mealType))),
        );
      }

      // Sort events by time
      filteredEvents.sort((a, b) => {
        const timeA = this.parseTime(a.time);
        const timeB = this.parseTime(b.time);
        return timeA - timeB;
      });

      // Format response
      const dayNames = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
      const dayName = dayNames[queryDate.getDay()];
      const formattedDate = queryDate.toLocaleDateString('en-US', {
        weekday: 'long',
        year: 'numeric',
        month: 'long',
        day: 'numeric',
      });

      return {
        date: formattedDate,
        dayName,
        dayType,
        readiness,
        shiftStart,
        shiftEnd,
        events: filteredEvents,
        summary: {
          workoutCount: workouts.filter(w => w.completed).length,
          mealCount: meals.length,
          recoveryCount: sleepRecovery.length,
          totalEvents: filteredEvents.length,
        },
      };
    } catch (error) {
      logger.error(`Get daily timeline error: ${error.message}`);
      throw error;
    }
  }

  /**
   * Reschedule event
   */
  static async rescheduleEvent(userId, eventData) {
    try {
      const { eventType, eventId, newTime, date } = eventData;

      if (!eventType || !eventId || !newTime) {
        throw new Error('Event type, event ID, and new time are required');
      }

      // Validate time format
      const timeRegex = /^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$/;
      if (!timeRegex.test(newTime)) {
        throw new Error('Invalid time format. Use HH:MM (24-hour format)');
      }

      const targetDate = date ? new Date(date) : new Date();
      targetDate.setHours(0, 0, 0, 0);

      let updatedEvent;

      // Check if eventId is a recommended task placeholder
      if (typeof eventId === 'string' && eventId.startsWith('rec_')) {
        if (eventType === 'workout') {
          let workout = await Workout.findOne({ category: 'recovery' });
          if (!workout) workout = await Workout.findOne();
          if (!workout) {
            workout = await Workout.create({
              title: 'Mid-Shift Express Workout',
              description: 'Quick recovery workout for shift workers.',
              durationMinutes: 20,
              category: 'recovery',
              intensity: 'medium',
              isPublic: true,
            });
          }
          updatedEvent = await WorkoutLog.create({
            userId,
            workoutId: workout._id,
            date: targetDate,
            scheduledTime: newTime,
            status: 'rescheduled',
            completed: false,
            durationMinutes: 20,
            completionPercentage: 0,
            isLogged: false
          });
        } else if (eventType === 'meal') {
          const title = eventId === 'rec_pre_shift_energizer' 
            ? 'Pre-Shift Energizer & Hydration' 
            : 'Mid-Shift Balanced Meal';
          const mealType = eventId === 'rec_pre_shift_energizer' ? 'pre_workout' : 'post_workout';
          updatedEvent = await Meal.create({
            userId,
            date: targetDate,
            title,
            scheduledTime: newTime,
            mealType,
            calories: eventId === 'rec_pre_shift_energizer' ? 150 : 500,
            protein: eventId === 'rec_pre_shift_energizer' ? 10 : 30,
            carbs: eventId === 'rec_pre_shift_energizer' ? 20 : 50,
            fat: eventId === 'rec_pre_shift_energizer' ? 3 : 15,
            foodId: null,
            quantity: 100,
            status: 'rescheduled'
          });
        } else if (eventType === 'recovery') {
          const title = eventId === 'rec_post_shift_wind_down'
            ? 'Post-Shift Recovery & Sleep Prep'
            : 'Mid-Shift Active Recovery Stretch';
          const durationMinutes = eventId === 'rec_post_shift_wind_down' ? 30 : 10;
          const activityKey = eventId === 'rec_post_shift_wind_down' ? 'wind_down' : 'active_recovery';
          
          const endTime = this.addMinutesToTime(newTime, durationMinutes);

          updatedEvent = await SleepLog.create({
            userId,
            date: targetDate,
            title,
            startTime: newTime,
            endTime,
            durationMinutes,
            quality: 'average',
            interruptionCount: 0,
            interruptionDurationMinutes: 0,
            sleepEfficiency: 100,
            readinessEffect: 10,
            activityKey,
            notes: 'Rescheduled recovery session'
          });
        }
        return updatedEvent;
      }

      switch (eventType) {
        case 'workout':
          updatedEvent = await WorkoutLog.findOneAndUpdate(
            { _id: eventId, userId },
            { scheduledTime: newTime, status: 'rescheduled' },
            { returnDocument: 'after' },
          );
          break;

        case 'meal':
          updatedEvent = await Meal.findOneAndUpdate(
            { _id: eventId, userId },
            { scheduledTime: newTime, status: 'rescheduled' },
            { returnDocument: 'after' },
          );
          break;

        case 'recovery':
          const recoveryActivity = await SleepLog.findById(eventId);
          if (!recoveryActivity) {
            throw new Error('Recovery activity not found');
          }

          const startTime = this.parseTime(newTime);
          const durationMs = recoveryActivity.durationMinutes * 60 * 1000;
          const newEndTime = new Date(startTime.getTime() + durationMs);

          const newEndTimeStr = `${newEndTime.getHours().toString().padStart(2, '0')}:${newEndTime.getMinutes().toString().padStart(2, '0')}`;

          updatedEvent = await SleepLog.findOneAndUpdate(
            { _id: eventId, userId },
            {
              startTime: newTime,
              endTime: newEndTimeStr,
              status: 'rescheduled',
            },
            { returnDocument: 'after' },
          );
          break;

        default:
          throw new Error('Invalid event type');
      }

      if (!updatedEvent) {
        throw new Error('Event not found or not authorized');
      }

      return updatedEvent;
    } catch (error) {
      logger.error(`Reschedule event error: ${error.message}`);
      throw error;
    }
  }

  /**
   * Complete event
   */
  static async completeEvent(userId, eventData) {
    try {
      const { eventType, eventId, date, time } = eventData;
      if (!eventType || !eventId) {
        throw new Error('Event type and event ID are required');
      }

      const targetDate = date ? new Date(date) : new Date();
      targetDate.setHours(0, 0, 0, 0);
      const startTimeStr = time || '12:00';

      let completedEvent;

      // Check if eventId is a recommended task placeholder
      if (typeof eventId === 'string' && eventId.startsWith('rec_')) {
        if (eventType === 'workout') {
          let workout = await Workout.findOne({ category: 'recovery' });
          if (!workout) workout = await Workout.findOne();
          if (!workout) {
            workout = await Workout.create({
              title: 'Mid-Shift Express Workout',
              description: 'Quick recovery workout for shift workers.',
              durationMinutes: 20,
              category: 'recovery',
              intensity: 'medium',
              isPublic: true,
            });
          }
          completedEvent = await WorkoutLog.create({
            userId,
            workoutId: workout._id,
            date: targetDate,
            scheduledTime: startTimeStr,
            status: 'completed',
            completed: true,
            durationMinutes: 20,
            completionPercentage: 100,
            isLogged: true
          });
        } else if (eventType === 'meal') {
          const title = eventId === 'rec_pre_shift_energizer' 
            ? 'Pre-Shift Energizer & Hydration' 
            : 'Mid-Shift Balanced Meal';
          const mealType = eventId === 'rec_pre_shift_energizer' ? 'pre_workout' : 'post_workout';
          completedEvent = await Meal.create({
            userId,
            date: targetDate,
            title,
            scheduledTime: startTimeStr,
            mealType,
            calories: eventId === 'rec_pre_shift_energizer' ? 150 : 500,
            protein: eventId === 'rec_pre_shift_energizer' ? 10 : 30,
            carbs: eventId === 'rec_pre_shift_energizer' ? 20 : 50,
            fat: eventId === 'rec_pre_shift_energizer' ? 3 : 15,
            foodId: null,
            quantity: 100,
            status: 'logged'
          });
        } else if (eventType === 'recovery') {
          const title = eventId === 'rec_post_shift_wind_down'
            ? 'Post-Shift Recovery & Sleep Prep'
            : 'Mid-Shift Active Recovery Stretch';
          const durationMinutes = eventId === 'rec_post_shift_wind_down' ? 30 : 10;
          const activityKey = eventId === 'rec_post_shift_wind_down' ? 'wind_down' : 'active_recovery';
          
          const endTime = this.addMinutesToTime(startTimeStr, durationMinutes);

          completedEvent = await SleepLog.create({
            userId,
            date: targetDate,
            title,
            startTime: startTimeStr,
            endTime,
            durationMinutes,
            quality: 'good',
            interruptionCount: 0,
            interruptionDurationMinutes: 0,
            sleepEfficiency: 100,
            readinessEffect: 15,
            activityKey,
            notes: 'Completed recovery session',
            status: 'completed'
          });
        }
        return completedEvent;
      }

      switch (eventType) {
        case 'workout':
          completedEvent = await WorkoutLog.findOneAndUpdate(
            { _id: eventId, userId },
            { completed: true, status: 'completed', completionPercentage: 100 },
            { returnDocument: 'after' }
          );
          break;

        case 'meal':
          completedEvent = await Meal.findOneAndUpdate(
            { _id: eventId, userId },
            { status: 'completed' },
            { returnDocument: 'after' }
          );
          break;

        case 'recovery':
          completedEvent = await SleepLog.findOneAndUpdate(
            { _id: eventId, userId },
            { status: 'completed' },
            { returnDocument: 'after' }
          );
          break;

        default:
          throw new Error('Invalid event type');
      }

      if (!completedEvent) {
        throw new Error('Event not found or not authorized');
      }

      return completedEvent;
    } catch (error) {
      logger.error(`Complete event error: ${error.message}`);
      throw error;
    }
  }

  /**
   * Get upcoming events (next 7 days)
   */
  static async getUpcomingEvents(userId, days = 7) {
    try {
      const startDate = new Date();
      startDate.setHours(0, 0, 0, 0);

      const endDate = new Date();
      endDate.setDate(endDate.getDate() + days);
      endDate.setHours(23, 59, 59, 999);

      // Fetch scheduled events
      const [scheduledWorkouts, scheduledMeals] = await Promise.all([
        WorkoutLog.find({
          userId,
          date: { $gte: startDate, $lte: endDate },
          scheduledTime: { $ne: null },
          completed: false,
        }).populate('workoutId', 'title durationMinutes'),

        Meal.find({
          userId,
          date: { $gte: startDate, $lte: endDate },
          scheduledTime: { $ne: null },
        }).populate('foodId', 'name'),
      ]);

      // Format events
      const events = [];

      scheduledWorkouts.forEach(workout => {
        events.push({
          id: workout._id,
          type: 'workout',
          date: workout.date,
          time: workout.scheduledTime,
          title: workout.workoutId?.title || 'Workout',
          subtitle: `${workout.workoutId?.durationMinutes || 30} min`,
          status: 'scheduled',
        });
      });

      scheduledMeals.forEach(meal => {
        events.push({
          id: meal._id,
          type: 'meal',
          date: meal.date,
          time: meal.scheduledTime,
          title: meal.title,
          subtitle: `${meal.mealType} • ${meal.calories} kcal`,
          status: 'scheduled',
        });
      });

      // Sort by date and time
      events.sort((a, b) => {
        const dateCompare = a.date - b.date;
        if (dateCompare !== 0) return dateCompare;

        const timeA = this.parseTime(a.time);
        const timeB = this.parseTime(b.time);
        return timeA - timeB;
      });

      // Group by date
      const eventsByDate = {};
      events.forEach(event => {
        const dateStr = event.date.toDateString();
        if (!eventsByDate[dateStr]) {
          eventsByDate[dateStr] = [];
        }
        eventsByDate[dateStr].push(event);
      });

      return {
        startDate,
        endDate,
        totalEvents: events.length,
        eventsByDate,
      };
    } catch (error) {
      logger.error(`Get upcoming events error: ${error.message}`);
      throw error;
    }
  }

  /**
   * Update schedule manually
   */
  static async updateSchedule(userId, date, updateData) {
    try {
      const scheduleDate = new Date(date);
      scheduleDate.setHours(0, 0, 0, 0);

      const schedule = await UserShiftSchedule.findOneAndUpdate(
        { userId, date: scheduleDate },
        {
          ...updateData,
          isAutoGenerated: false,
          updatedAt: new Date(),
        },
        { upsert: true, returnDocument: 'after' },
      );

      return schedule;
    } catch (error) {
      logger.error(`Update schedule error: ${error.message}`);
      throw error;
    }
  }

  /**
   * Get schedule statistics
   */
  static async getScheduleStats(userId, startDate, endDate) {
    try {
      const stats = await UserShiftSchedule.aggregate([
        {
          $match: {
            userId: new mongoose.Types.ObjectId(userId),
            date: { $gte: new Date(startDate), $lte: new Date(endDate) },
          },
        },
        {
          $group: {
            _id: '$dayType',
            count: { $sum: 1 },
          },
        },
      ]);

      // Calculate percentages
      const totalDays = stats.reduce((sum, stat) => sum + stat.count, 0);
      const statsWithPercentages = stats.map(stat => ({
        dayType: stat._id,
        count: stat.count,
        percentage: totalDays > 0 ? Math.round((stat.count / totalDays) * 100) : 0,
      }));

      return {
        period: { startDate, endDate },
        totalDays,
        stats: statsWithPercentages,
      };
    } catch (error) {
      logger.error(`Get schedule stats error: ${error.message}`);
      throw error;
    }
  }

  /**
   * Generate dynamic subtitle based on shift and sleep timing
   */
  static generateDynamicSubtitle(eventType, eventData, user, schedule, sleepLogs, eventTime) {
    try {
      // Safe fallback - use existing subtitle logic if data is missing
      if (!eventTime) {
        return this.getDefaultSubtitle(eventType, eventData);
      }

      // Parse event time to minutes since midnight
      const eventMinutes = this.timeToMinutes(eventTime);

      if (eventType === 'workout') {
        // Try to generate wake time based subtitle
        const wakeTime = this.getWakeTime(sleepLogs);

        if (wakeTime) {
          const wakeMinutes = this.timeToMinutes(wakeTime);
          const diffMinutes = eventMinutes - wakeMinutes;

          if (diffMinutes > 0) {
            // After wake
            const hours = Math.floor(diffMinutes / 60);
            const minutes = diffMinutes % 60;

            if (hours > 0) {
              return `+${hours}h ${minutes}m after wake`;
            } else {
              return `+${minutes}m after wake`;
            }
          } else if (diffMinutes < 0) {
            // Before wake (unusual case)
            const absDiff = Math.abs(diffMinutes);
            const hours = Math.floor(absDiff / 60);
            const minutes = absDiff % 60;

            if (hours > 0) {
              return `-${hours}h ${minutes}m before wake`;
            } else {
              return `-${minutes}m before wake`;
            }
          }
        }

        // Fallback to default
        return this.getDefaultSubtitle(eventType, eventData);
      }

      if (eventType === 'meal') {
        // Try to generate shift time based subtitle
        const shiftStartTime = schedule?.shiftStart;

        if (shiftStartTime) {
          const shiftStartMinutes = this.timeToMinutes(shiftStartTime);
          const diffMinutes = eventMinutes - shiftStartMinutes;

          if (diffMinutes < 0) {
            // Before shift start (Pre-Shift Fuel)
            const absDiff = Math.abs(diffMinutes);
            const hours = Math.floor(absDiff / 60);
            const minutes = absDiff % 60;

            if (hours > 0) {
              return `-${hours}h ${minutes}m before shift`;
            } else {
              return `-${minutes}m before shift`;
            }
          } else if (diffMinutes > 0) {
            // After shift start
            const hours = Math.floor(diffMinutes / 60);
            const minutes = diffMinutes % 60;

            if (hours > 0) {
              return `+${hours}h ${minutes}m after shift start`;
            } else {
              return `+${minutes}m after shift start`;
            }
          }
        }

        // Fallback to default
        return this.getDefaultSubtitle(eventType, eventData);
      }

      if (eventType === 'recovery') {
        // Try to generate shift relative subtitle
        const shiftStartTime = schedule?.shiftStart;
        const shiftEndTime = schedule?.shiftEnd;

        if (shiftEndTime) {
          const shiftEndMinutes = this.timeToMinutes(shiftEndTime);

          if (eventMinutes > shiftEndMinutes) {
            return 'Post Shift';
          }
        }

        if (shiftStartTime) {
          const shiftStartMinutes = this.timeToMinutes(shiftStartTime);

          if (eventMinutes < shiftStartMinutes) {
            return 'Pre Shift';
          }
        }

        // Fallback to default
        return this.getDefaultSubtitle(eventType, eventData);
      }

      // Default fallback
      return this.getDefaultSubtitle(eventType, eventData);
    } catch (error) {
      // Safe fallback on any error
      return this.getDefaultSubtitle(eventType, eventData);
    }
  }

  /**
   * Get default subtitle (original logic)
   */
  static getDefaultSubtitle(eventType, eventData) {
    if (eventType === 'workout') {
      return eventData.completed
        ? `Completed ${eventData.durationMinutes || eventData.workoutId?.durationMinutes} min`
        : 'Scheduled workout';
    }

    if (eventType === 'meal') {
      return `${eventData.mealType.charAt(0).toUpperCase() + eventData.mealType.slice(1)} • ${eventData.calories} kcal`;
    }

    if (eventType === 'recovery') {
      return `${eventData.durationMinutes} min • ${eventData.quality} quality`;
    }

    return 'Event';
  }

  /**
   * Get wake time from sleep logs (latest endTime of night sleep or daytime sleep)
   */
  static getWakeTime(sleepLogs) {
    if (!sleepLogs || sleepLogs.length === 0) {
      return null;
    }

    // Find the latest sleep activity (night_sleep or daytime_sleep)
    const sleepActivities = sleepLogs.filter(
      log => log.activityKey === 'night_sleep' || log.activityKey === 'daytime_sleep',
    );

    if (sleepActivities.length === 0) {
      return null;
    }

    // Get the one with the latest end time
    const latestSleep = sleepActivities.reduce((latest, current) => {
      const latestEndMinutes = this.timeToMinutes(latest.endTime);
      const currentEndMinutes = this.timeToMinutes(current.endTime);
      return currentEndMinutes > latestEndMinutes ? current : latest;
    });

    return latestSleep.endTime;
  }

  /**
   * Convert time string (HH:MM) to minutes since midnight
   */
  static timeToMinutes(timeStr) {
    if (!timeStr) return 0;
    const [hours, minutes] = timeStr.split(':').map(Number);
    return hours * 60 + minutes;
  }

  /**
   * Convert minutes since midnight to time string (HH:MM)
   */
  static minutesToTime(minutes) {
    const h = Math.floor(minutes / 60).toString().padStart(2, '0');
    const m = (minutes % 60).toString().padStart(2, '0');
    return `${h}:${m}`;
  }

  /**
   * Add/subtract minutes from HH:MM time string
   */
  static addMinutesToTime(timeStr, minutes) {
    if (!timeStr) return '12:00';
    const totalMinutes = (this.timeToMinutes(timeStr) + minutes + 1440) % 1440;
    return this.minutesToTime(totalMinutes);
  }

  /**
   * Helper function to parse time string to Date object
   */
  static parseTime(timeStr) {
    const [hours, minutes] = timeStr.split(':').map(Number);
    const date = new Date();
    date.setHours(hours, minutes, 0, 0);
    return date;
  }

  /**
   * Helper function to format time
   */
  static formatTime(date) {
    const hours = date.getHours().toString().padStart(2, '0');
    const minutes = date.getMinutes().toString().padStart(2, '0');
    return `${hours}:${minutes}`;
  }
}

module.exports = CalendarService;
