const mongoose = require('mongoose');

const userShiftScheduleSchema = new mongoose.Schema(
    {
        userId: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'User',
            required: true,
        },
        date: {
            type: Date,
            required: true,
        },
        dayType: {
            type: String,
            enum: ['work', 'rotation', 'recovery', 'off'],
            required: true,
        },
        taskType: {
            type: String,
            enum: ['suggested', 'fixed', 'completed', 'missed', 'expired', 'rescheduled'],
            default: 'suggested',
        },
        title: {
            type: String,
            default: null,
        },
        description: {
            type: String,
            default: null,
        },
        shiftStart: {
            type: String, // Format: "HH:MM"
            default: null,
        },
        shiftEnd: {
            type: String, // Format: "HH:MM"
            default: null,
        },
        scheduledStart: {
            type: Date,
            default: null,
        },
        scheduledEnd: {
            type: Date,
            default: null,
        },
        sourceModule: {
            type: String,
            default: 'calendar',
        },
        sourceId: {
            type: String,
            default: null,
        },
        dependency: {
            type: String,
            default: null,
        },
        status: {
            type: String,
            enum: ['suggested', 'fixed', 'completed', 'missed', 'expired', 'rescheduled'],
            default: 'suggested',
        },
        priority: {
            type: String,
            enum: ['low', 'medium', 'high'],
            default: 'medium',
        },
        deepLink: {
            type: String,
            default: null,
        },
        notes: {
            type: String,
            default: null,
        },
        isAutoGenerated: {
            type: Boolean,
            default: true,
        },
        createdAt: {
            type: Date,
            default: Date.now,
        },
        updatedAt: {
            type: Date,
            default: Date.now,
        },
    },
    { timestamps: true, versionKey: false },
);

// Compound unique index for userId and date
userShiftScheduleSchema.index({ userId: 1, date: 1 }, { unique: true });
// Index for querying by dayType
userShiftScheduleSchema.index({ userId: 1, dayType: 1 });

const UserShiftSchedule = mongoose.model('UserShiftSchedule', userShiftScheduleSchema);

module.exports = UserShiftSchedule;
